import type { Command } from 'commander';
import chalk from 'chalk';
import { execaCommandSync } from 'execa';
import { listAllSessions, getAgentSessionReport } from '../lib/session.js';
import { gitCurrentBranch, isGitRepo } from '../lib/git.js';
import type { AgentType } from '../lib/provider.js';

export function registerPrCommand(program: Command): void {
  program
    .command('pr [session-id]')
    .description('Create a GitHub Pull Request from agent session changes')
    .option('--draft', 'Create as draft PR (default: true)', true)
    .option('--no-draft', 'Create as ready PR')
    .option('-b, --base <branch>', 'Base branch (default: main)')
    .option('-a, --agent <type>', 'Agent type: copilot | claude')
    .option('--dry-run', 'Show PR details without creating')
    .action((sessionId: string | undefined, opts) => {
      try {
        createPr(sessionId, opts);
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error(chalk.red(`  ✗ ${msg}`));
      }
    });
}

function createPr(
  sessionId: string | undefined,
  opts: { draft?: boolean; base?: string; agent?: string; dryRun?: boolean },
): void {
  const sessions = listAllSessions(50);
  let targetSession;

  if (sessionId) {
    targetSession = sessions.find(s => s.id.startsWith(sessionId));
  } else {
    targetSession = sessions[0];
    if (targetSession) {
      console.log(chalk.dim(`  Using latest session: ${targetSession.id.slice(0, 12)}…\n`));
    }
  }

  if (!targetSession) {
    console.log(chalk.red('  ✗ No session found'));
    return;
  }

  const agentType = (opts.agent || targetSession.agent) as AgentType | undefined;
  const report = getAgentSessionReport(targetSession.id, agentType);
  if (!report) {
    console.log(chalk.red('  ✗ Could not load session report'));
    return;
  }

  const cwd = report.cwd;
  if (!cwd || !isGitRepo(cwd)) {
    console.log(chalk.red('  ✗ Not a git repository'));
    return;
  }

  const currentBranch = gitCurrentBranch(cwd);
  const baseBranch = opts.base || 'main';

  if (!currentBranch || currentBranch === baseBranch) {
    console.log(chalk.yellow(`  ⚠ Currently on ${baseBranch} — switch to a feature branch first`));
    return;
  }

  // Build PR title from session
  const agentName = report.agent === 'claude' ? 'Claude' : 'Copilot';
  const title = report.summary
    ? report.summary.slice(0, 72)
    : `[${agentName}] ${currentBranch.replace('agent/', '').replace(/-/g, ' ').slice(0, 60)}`;

  // Build PR body
  const bodyParts: string[] = [];
  bodyParts.push(`## 🤖 Auto-generated by copilot-agent (${report.agent})\n`);

  if (report.summary) {
    bodyParts.push(`**Task:** ${report.summary}\n`);
  }

  bodyParts.push('### Stats');
  bodyParts.push(`- **Duration:** ${formatDur(report.durationMs)}`);
  bodyParts.push(`- **Turns:** ${report.assistantTurns}`);
  bodyParts.push(`- **Tokens:** ${report.outputTokens.toLocaleString()}`);
  bodyParts.push(`- **Premium requests:** ${report.premiumRequests}`);
  bodyParts.push('');

  if (report.gitCommits.length > 0) {
    bodyParts.push('### Commits');
    for (const c of report.gitCommits.slice(0, 20)) {
      bodyParts.push(`- ${c.split('\n')[0]}`);
    }
    bodyParts.push('');
  }

  if (report.filesCreated.length > 0 || report.filesEdited.length > 0) {
    bodyParts.push('### Files Changed');
    for (const f of report.filesCreated.slice(0, 15)) bodyParts.push(`- ➕ ${f}`);
    for (const f of report.filesEdited.slice(0, 15)) bodyParts.push(`- ✏️ ${f}`);
    bodyParts.push('');
  }

  if (report.taskCompletions.length > 0) {
    bodyParts.push('### Tasks Completed');
    for (const t of report.taskCompletions.slice(0, 10)) {
      bodyParts.push(`- ✅ ${t.split('\n')[0]}`);
    }
    bodyParts.push('');
  }

  bodyParts.push(`---\n*Session: \`${report.id.slice(0, 12)}…\`*`);

  const body = bodyParts.join('\n');

  // Display preview
  console.log(chalk.bold.cyan('  📝 Pull Request Preview\n'));
  console.log(`  ${chalk.bold('Title:')}  ${title}`);
  console.log(`  ${chalk.bold('Branch:')} ${chalk.cyan(currentBranch)} → ${chalk.green(baseBranch)}`);
  console.log(`  ${chalk.bold('Draft:')}  ${opts.draft ? 'yes' : 'no'}`);
  console.log(`  ${chalk.bold('Agent:')}  ${report.agent}`);
  console.log(`  ${chalk.bold('Files:')}  ${chalk.green(`+${report.filesCreated.length}`)} created, ${chalk.yellow(`~${report.filesEdited.length}`)} edited`);
  console.log(`  ${chalk.bold('Commits:')} ${report.gitCommits.length}`);
  console.log();

  if (opts.dryRun) {
    console.log(chalk.dim('  (dry run — PR not created)'));
    console.log(chalk.dim('\n  Body preview:'));
    console.log(chalk.dim(body.split('\n').map(l => `    ${l}`).join('\n')));
    return;
  }

  // Push branch
  try {
    console.log(chalk.dim('  Pushing branch...'));
    execaCommandSync(`git push -u origin ${currentBranch}`, { cwd });
  } catch {
    // May already be pushed
  }

  // Create PR with gh CLI
  try {
    const ghArgs = [
      'gh', 'pr', 'create',
      '--title', title,
      '--body', body,
      '--base', baseBranch,
      '--label', 'automated',
    ];
    if (opts.draft) ghArgs.push('--draft');

    const result = execaCommandSync(
      ghArgs.map(a => (a.includes(' ') ? `"${a}"` : a)).join(' '),
      { cwd },
    );
    const prUrl = result.stdout.trim();
    console.log(chalk.green(`  ✔ PR created: ${prUrl}`));
  } catch (err: unknown) {
    const msg =
      err instanceof Error ? ((err as any).stderr as string) || err.message : String(err);
    console.log(chalk.red(`  ✗ Failed to create PR: ${msg}`));
    console.log(chalk.dim('  Make sure gh CLI is installed and authenticated'));
  }
}

function formatDur(ms: number): string {
  if (ms < 60_000) return `${Math.round(ms / 1000)}s`;
  if (ms < 3_600_000) return `${Math.round(ms / 60_000)}m`;
  const h = Math.floor(ms / 3_600_000);
  const m = Math.round((ms % 3_600_000) / 60_000);
  return `${h}h ${m}m`;
}
